export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const PLATE_NUMBER_ENTER = 'PLATE_NUMBER_ENTER';
export const USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED';
export const USER_PASSWORD_REQUIRED = 'USER_PASSWORD_REQUIRED';
